### ISSUE TITLE
`vrfy` explodes if `vrfy/logging/catalog.log` file is missing

### ISSUE THREAD

**Issue by Gastove** [ifjorissen/vrfy#179]
If you haven't manually created the log file, you'll get:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/django/utils/log.py", line 86, in configure_logging
    logging_config_func(logging_settings)
  File "/opt/python/3.4.2/lib/python3.4/logging/config.py", line 789, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/python/3.4.2/lib/python3.4/logging/config.py", line 565, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'catalog_log': [Errno 2] No such file or directory: '/home/travis/build/Gastove/vrfy/logging/catalog.log'
```

**Comment by Gastove** [comment]
Ugh, this might not be easily un-bork-able. Mostly, it affects setting up the project -- new users and Travis. Hrm.

**Comment by Gastove** [comment]
Hacked this for travis with a lil' `mkdir logging && touch`. Not sure what to do about it in the long term; closing for now.
